//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc_backup
    {
        public string mamh { get; set; }
        public string tenmh { get; set; }
        public Nullable<byte> sotiet { get; set; }
    }
}
